export const UPDATE_STORIES = 'UPDATE_STORIES';
export const UPDATE_NOTES = 'UPDATE_NOTES';
export const UPDATE_CURRENT_STORY= 'UPDATE_CURRENT_STORY';

//export const ADD_NOTE_TO_STORY= 'ADD_NOTE_TO_STORY';

